### ISSUE TITLE
大佬 这边是要去接码平台 申请个号码

### ISSUE THREAD

**Issue by 362024758** [mtdhb/eleme#1]
npx ts-node example/get.ts
(node:26342) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/mtdhb/eleme/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/mtdhb/eleme/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/mtdhb/eleme/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:26342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
启动不了原因是 要申请个手机号码吗？

填在下面这段吗？

 const validateToken = await request.sendMobileCode(
    "从接码平台获取一个手机号填到这里"
  );
  if (validateToken) {
    console.log(validateToken);
    const userId = await request.loginByMobile(
      "从接码平台获得短信验证码填到这里"
    );

**Comment by zhuweiyou** [comment]
这只是示例代码，需要自己完善逻辑哦。是要接入接码平台的 API

**Comment by zhuweiyou** [comment]
> @zhuweiyou 请问一下大大,现在饿了么逻辑是接一下码,后面可以一直用这个cookie领取,还是需要每用这个cookie领取一次,接一次码

接了以后就可以一直领取了，不需要每次接。除非这个手机号绑到别的openid上了。
